# terraform remote config -backend=s3 -backend-config="bucket=anatta_shared_state" -backend-config="key=app.tfstate"

region = "us-east-1"
key_name = "anatta"
proxy_ami_id = "ami-e4e6c2f3"
proxy_instance_type = "t2.micro"
proxy_asg_desired = "1"
proxy_asg_min = "1"
proxy_asg_max = "1"
websvcs_ami_id = "ami-eee6c2f9"
websvcs_instance_type = "t2.micro"
websvcs_asg_desired = "2"
websvcs_asg_min = "1"
websvcs_asg_max = "3"
atlas_infrastructure = "marsupermammal/hashidemo"
